version: '3.8'

services:
  # Alterado para hífen para bater com os teus comandos de terminal
  merkadu-api:
    image: node:18-alpine
    container_name: merkadu-api
    restart: always
    working_dir: /app
    volumes:
      - ./merkadu-server:/app
    ports:
      - "3000:3000"
    # Adicionado 'ls' para confirmar a pasta no log
    command: sh -c "ls apps/server && cd apps/server && npm install && npm start"

  merkadu-web:
    image: node:18-alpine
    container_name: merkadu-web
    restart: always
    working_dir: /app
    volumes:
      - ./merkadu-server:/app
    ports:
      - "80:3000"
    command: sh -c "ls apps/storefront && cd apps/storefront && npm install && npm run build && npm start"