services:
  # O Motor da Loja (Vendure)
  vendure_worker:
    # ... as suas variáveis de ambiente ...
    working_dir: /app/server
    volumes:
      - ./merkadu-server:/app # Mapeia a raiz para termos acesso a apps/server
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"

  # O Site para os clientes (Next.js)
  merkadu_storefront:
    # ... as suas variáveis de ambiente ...
    working_dir: /app/storefront
    volumes:
      - ./merkadu-server/apps/storefront:/app/storefront # Mapeia diretamente a pasta storefront
    ports:
      - "80:3000" # Expondo a porta 80 para o browser
    command: sh -c "npm install && npm run build && npm start"