version: '3.8'

services:
  merkadu-api:
    image: node:18-alpine
    container_name: merkadu-api
    restart: always
    # ESTA É A LINHA QUE FALTA:
    env_file: .env
    working_dir: /app
    volumes:
      - /home/ec2-user/merkadu/merkadu-server:/app
    ports:
      - "3000:3000"
    command: sh -c "cd apps/server && npm install && npm run build && npm start"

  merkadu-web:
    image: node:18-alpine
    container_name: merkadu-web
    restart: always
    # Também recomendável para o frontend
    env_file: .env
    working_dir: /app
    volumes:
      - /home/ec2-user/merkadu/merkadu-server:/app
    ports:
      - "80:3000"
    command: sh -c "cd apps/storefront && npm install && npm run build && npm start"