services:
  merkadu-api:
    build: 
      context: ./merkadu-server/apps/server
      dockerfile: ../../Dockerfile
      args:
        - NODE_OPTIONS=--max-old-space-size=2048
    container_name: merkadu-api
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
      - "3002:3002"

  merkadu-web:
    build:
      context: ./merkadu-server/apps/storefront
      dockerfile: ../../Dockerfile
      args:
        - NODE_OPTIONS=--max-old-space-size=2048
        - VENDURE_SHOP_API_URL=${VENDURE_SHOP_API_URL}
        - NEXT_PUBLIC_VENDURE_SHOP_API_URL=${NEXT_PUBLIC_VENDURE_SHOP_API_URL}
    container_name: merkadu-web
    restart: always
    env_file: .env
    ports:
      - "80:3000"