version: '3.8'

services:
  # Back-end (Vendure)
  merkadu_api:
    image: node:18-alpine
    container_name: merkadu-api
    restart: always
    working_dir: /app/apps/server
    volumes:
      - ./merkadu-server:/app
    environment:
      - DB_HOST=${RDS_HOSTNAME}
      - DB_PORT=5432
      - DB_NAME=merkadu
      - DB_USER=postgres
      - DB_PASSWORD=${RDS_PASSWORD}
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"

  # Front-end (Next.js)
  merkadu_web:
    image: node:18-alpine
    container_name: merkadu-web
    restart: always
    working_dir: /app/apps/storefront
    volumes:
      - ./merkadu-server:/app
    ports:
      - "80:3000" # Expondo na porta 80 para acesso direto pelo IP
    environment:
      - NEXT_PUBLIC_API_URL=http://${EC2_PUBLIC_IP}:3000/shop-api
    command: sh -c "npm install && npm run build && npm start"