name: Deploy Merkadu to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Copiar ficheiros para EC2 via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          # Enviamos o código e a configuração do Docker
          source: "merkadu-server,docker-compose.yml"
          target: "~/merkadu"

      - name: Executar Docker na EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          # VITAL: Aumentamos o timeout para 40 minutos para builds pesados em t3.micro
          command_timeout: 40m
          script: |
            cd ~/merkadu
            
            # 1. Para os serviços atuais para libertar RAM
            docker-compose down
            
            # 2. Build sequencial para não sobrecarregar o CPU/RAM
            # Primeiro a API (Backend)
            docker-compose build merkadu-api
            
            # Depois a Web (Storefront) - Esta é a parte que consome mais memória
            docker-compose build merkadu-web
            
            # 3. Sobe os serviços em segundo plano (detach mode)
            docker-compose up -d
            
            # 4. Limpeza de imagens antigas para preservar os 11GB de disco
            docker image prune -f